# Generated by Django 6.0.2 on 2026-02-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Subject',
            new_name='subject',
        ),
    ]
